// <auto-generated />
namespace WPF_HOME.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SampleMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SampleMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201708300934472_SampleMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
